#!/usr/bin/env python3

"""Generate deterministic NSIS commands and an installed ownership manifest."""

from __future__ import annotations

import argparse
from pathlib import Path, PureWindowsPath


def nsis_relative_path(root: Path, path: Path) -> str:
    relative = PureWindowsPath(path.relative_to(root))
    # MSYS2 Python may stringify Windows paths with forward slashes. NSIS and
    # the ownership reader require backslashes regardless of the build host.
    value = "\\".join(relative.parts)
    forbidden = {'<', '>', ':', '"', '/', '|', '?', '*', '$', '\r', '\n', '\0'}
    if any(character in value for character in forbidden):
        raise ValueError(f"NSIS-unsafe packaged path: {value!r}")
    if any(part in {"", ".", ".."} for part in relative.parts):
        raise ValueError(f"Unsafe packaged path component: {value!r}")
    return value


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("runtime_directory", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("ownership_manifest", type=Path)
    args = parser.parse_args()

    runtime_directory = args.runtime_directory.resolve(strict=True)
    if not runtime_directory.is_dir():
        raise ValueError(f"Runtime path is not a directory: {runtime_directory}")

    files = sorted(
        (
            nsis_relative_path(runtime_directory, path)
            for path in runtime_directory.rglob("*")
            if path.is_file()
        ),
        key=str.casefold,
    )
    if not files:
        raise ValueError(f"Runtime directory is empty: {runtime_directory}")

    ownership_files = [
        *files,
        "logo.ico",
        "uninstall.exe",
        ".memento-study-edition-install",
        # Keep the manifest last so a partial-recovery reader can delete every
        # preceding owned file before deleting the manifest it is reading.
        ".memento-study-edition-owned-files",
    ]
    if len({value.casefold() for value in ownership_files}) != len(
        ownership_files
    ):
        raise ValueError("Ownership manifest contains duplicate Windows paths")

    directories = sorted(
        (
            nsis_relative_path(runtime_directory, path)
            for path in runtime_directory.rglob("*")
            if path.is_dir()
        ),
        key=lambda value: (-value.count("\\"), value.casefold()),
    )
    shallow_directories = sorted(
        directories,
        key=lambda value: (value.count("\\"), value.casefold()),
    )

    lines = [
        "; Generated by windows/generate-nsis-file-list.py. Do not edit.",
        "!macro MementoCheckPortableFiles FAILURE_LABEL",
    ]
    lines.extend(
        f'\t!insertmacro MementoCheckOwnedFile "$INSTDIR\\{path}" ${{FAILURE_LABEL}}'
        for path in files
    )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoDeletePortableFiles FAILURE_LABEL",
        ]
    )
    lines.extend(
        f'\t!insertmacro MementoDeleteOwnedFile "$INSTDIR\\{path}" ${{FAILURE_LABEL}}'
        for path in files
    )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoCreateBackupPortableDirectories FAILURE_LABEL",
        ]
    )
    lines.extend(
        (
            f'\tPush "$PLUGINSDIR\\memento-previous-files\\{path}"\n'
            "\tCall EnsureInstallDirectory\n"
            "\tStrCmp $OperationResult \"0\" 0 ${FAILURE_LABEL}"
        )
        for path in shallow_directories
    )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoBackupPortableFiles FAILURE_LABEL",
        ]
    )
    for index, path in enumerate(files):
        lines.extend(
            [
                f'\tIfFileExists "$INSTDIR\\{path}" 0 memento_backup_portable_{index}_done',
                f'\t!insertmacro MementoCopyFileNoOverwrite "$INSTDIR\\{path}" "$PLUGINSDIR\\memento-previous-files\\{path}" ${{FAILURE_LABEL}}',
                f"\tmemento_backup_portable_{index}_done:",
            ]
        )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoRestoreBackupPortableFiles FAILURE_LABEL",
        ]
    )
    for index, path in enumerate(files):
        lines.extend(
            [
                f'\tIfFileExists "$PLUGINSDIR\\memento-previous-files\\{path}" 0 memento_restore_portable_{index}_done',
                f'\tIfFileExists "$INSTDIR\\{path}" 0 memento_restore_portable_{index}_copy',
                f'\tStrCmp $PreviousRemovalCompleted "1" ${{FAILURE_LABEL}} memento_restore_portable_{index}_done',
                f"\tmemento_restore_portable_{index}_copy:",
                f'\t!insertmacro MementoCopyFileNoOverwrite "$PLUGINSDIR\\memento-previous-files\\{path}" "$INSTDIR\\{path}" ${{FAILURE_LABEL}}',
                f"\tmemento_restore_portable_{index}_done:",
            ]
        )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoValidatePortableDirectories FAILURE_LABEL",
        ]
    )
    lines.extend(
        (
            f'\tIfFileExists "$INSTDIR\\{path}" 0 +4\n'
            f'\tPush "$INSTDIR\\{path}"\n'
            "\tCall ValidateExistingDirectory\n"
            "\tStrCmp $OperationResult \"0\" 0 ${FAILURE_LABEL}"
        )
        for path in shallow_directories
    )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoValidateUninstallPortableDirectories FAILURE_LABEL",
        ]
    )
    lines.extend(
        (
            f'\tIfFileExists "$INSTDIR\\{path}" 0 +4\n'
            f'\tPush "$INSTDIR\\{path}"\n'
            "\tCall un.ValidateExistingDirectory\n"
            "\tStrCmp $OperationResult \"0\" 0 ${FAILURE_LABEL}"
        )
        for path in shallow_directories
    )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoValidateStagedPortableDirectories FAILURE_LABEL",
        ]
    )
    lines.extend(
        (
            f'\tIfFileExists "$INSTDIR\\${{STAGEDIR}}\\{path}" 0 +4\n'
            f'\tPush "$INSTDIR\\${{STAGEDIR}}\\{path}"\n'
            "\tCall ValidateExistingDirectory\n"
            "\tStrCmp $OperationResult \"0\" 0 ${FAILURE_LABEL}"
        )
        for path in shallow_directories
    )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoCheckPortableInstallCollisions FAILURE_LABEL",
        ]
    )
    lines.extend(
        f'\t!insertmacro MementoCheckInstallCollision "$INSTDIR\\{path}" ${{FAILURE_LABEL}}'
        for path in files
    )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoRequireStagedPortableFiles FAILURE_LABEL",
        ]
    )
    lines.extend(
        f'\t!insertmacro MementoRequireFile "$INSTDIR\\${{STAGEDIR}}\\{path}" ${{FAILURE_LABEL}}'
        for path in files
    )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoCreatePortableDirectories FAILURE_LABEL",
        ]
    )
    lines.extend(
        (
            f'\tPush "$INSTDIR\\{path}"\n'
            "\tCall EnsureInstallDirectory\n"
            "\tStrCmp $OperationResult \"0\" 0 ${FAILURE_LABEL}"
        )
        for path in shallow_directories
    )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoMoveStagedPortableFiles FAILURE_LABEL",
        ]
    )
    lines.extend(
        f'\t!insertmacro MementoMoveStagedFile "$INSTDIR\\${{STAGEDIR}}\\{path}" "$INSTDIR\\{path}" ${{FAILURE_LABEL}}'
        for path in files
    )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoRollbackStagedPortableFiles FAILURE_LABEL",
        ]
    )
    for index, path in enumerate(files):
        lines.extend(
            [
                f'\tIfFileExists "$INSTDIR\\${{STAGEDIR}}\\{path}" memento_rollback_portable_{index}_done',
                f'\t!insertmacro MementoDeleteOwnedFile "$INSTDIR\\{path}" ${{FAILURE_LABEL}}',
                f"\tmemento_rollback_portable_{index}_done:",
            ]
        )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoDeleteStagedPortableFiles FAILURE_LABEL",
        ]
    )
    lines.extend(
        f'\t!insertmacro MementoDeleteOwnedFile "$INSTDIR\\${{STAGEDIR}}\\{path}" ${{FAILURE_LABEL}}'
        for path in files
    )
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoRemovePortableDirectories",
        ]
    )
    lines.extend(f'\tRMDir "$INSTDIR\\{path}"' for path in directories)
    lines.extend(
        [
            "!macroend",
            "",
            "!macro MementoRemoveStagedPortableDirectories",
        ]
    )
    lines.extend(
        f'\tRMDir "$INSTDIR\\${{STAGEDIR}}\\{path}"' for path in directories
    )
    lines.extend(["!macroend", ""])

    args.output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    args.ownership_manifest.write_text(
        "\n".join(ownership_files) + "\n",
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    main()
